# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python 3.9 - Ubuntu Latest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:

  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout net_models
        uses: actions/checkout@v2
        with:
          repository: mihudec/net_models
          path: './net_models'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Install net_models
        run: |
          cd ./net_models/
          python setup.py install
          cd ..

      - name: Install Nuaal for legacy tests
        run: |
          pip install nuaal

      - name: Checkout net_parser
        uses: actions/checkout@v2

      - name: Install Test Dependencies
        run: |
          if [ -f tests/test-requirements.txt ]; then pip install -r tests/test-requirements.txt; fi

      - name: Run Unittests with coverage in tests
        run: |
          coverage run --omit venv/*,tests/* -m unittest discover -s ./tests -p test_*.py

      - name: Coverage Report
        run: |
          coverage report



